### PR TITLE
Updates for elastix.m and scimat_load.m

### PR DESCRIPTION
**Pull request by ingiehong**
Hi Ramon, huge thanks to the great contribution.

1/ Some updates to elastix.m. Due to a current limit to function of elastix, multiple-channel registration results in only one channel output. Transformix is used to transform other channels.
2/ Minor bugfix in scimat_load.m. fseek() requires proper ElementType information to correctly navigate within image file.

### CODE REVIEW

**Comment by rcasero** [comment]
Hi ingiehong,

Sorry for the very slow reply (I have been catching up with work after some time away).

Many thanks for your contributions, good work. The changes to scimat_load.m are fine, and I'll merge them.

However, the change to elastix.m is more problematic. The purpose of elastix.m is to register two images in the sense of computing the transform that aligns them. The main output is the transform, the deformed image produced by the elastix binary is just a side product.

If one wants to then apply the transform to the moving image, that's what transformix.m is for. If the image is RGB, transformix.m will produce an RGB image.

The reason for this is that applying transformix adds substantial computational cost. This may not be desired. For example, we work aligning stacks of histology images. We may need several sweeps of the stack registering each slice to its neighbours. But we don't really need to produce the colour deformed images after every sweep. It's faster to first compute a transform in every sweep, and then compose the transforms and apply them all together to the initial images.

I'll discuss this in our group meeting anyway.

Incidentally, we don't have experience with pull requests, the project got into git recently. Any advice on how to merge your scimat_load.m commit, but not the elastix.m one?

Cheers,

Ramon.

**Comment by ingiehong** [comment]
Hi Ramon! 
I agree, there probably is too much overhead regarding the multi-channel transformation. 
What if we added a field in the OPT structure to allow return of multi-channel registered images? 
OPT.returnMultichannel=true 
would return an image from multi-channel registration. Thanks again for the great work!
Best,
Ingie

**Comment by rcasero** [comment]
I think that could work. But there shouldn't be "ad hoc" code to transform the image, because that just duplicates transformix.m.

Basically, all we'd want is something like OPT.returnMultichannel=false by default, and then

if (OPT.returnMultichannel)
  transformix(...)
end

I think I'll be able to merge one of your commits and not the other with git-cherry-pick, but I haven't looked into it yet.

**Comment by rcasero** [comment]
OK, in the end I just had to revert the elastix.m commit, and I have pushed the other one. If you want to try again with elastix.m as discussed, you are very welcome. Sorry it took a bit to integrate your bug fix, and many thanks for your help.

**Pull request merged**
